name: ML_in_political_science
channels:
  - conda-forge
dependencies:
  - python=3.7.*
  - numpy=1.18.*
  - pandas=1.0.*
  - pandas-profiling=2.8.*
  - matplotlib=3.2.*
  - seaborn=0.10.*
  - scikit-learn=0.22.*
  - scipy=1.4.*
  - tqdm=4.43.*
  - ipython
  - jupyter